# .pre-commit-hooks.yaml
- id: check-clickup-id
  name: check clickup id
  description: prevents commits without clickup-id in message.
  entry: hooks/check_clickup_id.sh
  language: script
  types: [text]
  stages: [commit, push, manual]